// Code generated by encore. DO NOT EDIT.

package api

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	Create(ctx context.Context, p CreateBillRequest) (GetBillResponse, error)

	GetBillAPI(ctx context.Context, id string) (*GetBillResponse, error)

	AddItem(ctx context.Context, id string, p AddItemRequest) error

	Close(ctx context.Context, id string) error

	ListBills(ctx context.Context, p ListBillsRequest) (ListBillsResponse, error)
}
